<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>a87e357f-9522-4abe-b31a-91c9f2e7f8f4</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Altinn.ApiClients.Dialogporten.ServiceOwner" Version="1.117.1-alpha.1781004626" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    </ItemGroup>
</Project>
