<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>176ff11a-599b-4ca3-86da-f9099a82f515</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Altinn.ApiClients.Dialogporten.EndUser" Version="0.0.99" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
