<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>0071fdbc-5528-4da7-91a7-2c60762a4122</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Altinn.ApiClients.Dialogporten.EndUser" Version="1.118.7-alpha.1784896114" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
